default['blogapp']['venv'] = "/opt/blogapp/env"
default['blogapp']['app'] =  "/opt/blogapp/app"
default['blogapp']['log'] =  "/var/log/blogapp"
default['blogapp']['user'] =  "root"
default['blogapp']['group'] =  "root"
