---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: precise64
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://files.vagrantup.com/precise64.box
suites:
- name: sensu
  run_list:
    - role[sensu-server]
- name: blogapp
  run_list:
    - recipe[website::blogapp]
